FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy app
COPY . .

# Build Next.js
RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]  # starts Next.js in SSR mode
